spring:
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 20
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 3s
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 0
          max-wait: 5s

    stripe:
      secret: ${STRIPE_SECRET}
      success_callback: ${STRIPE_SUCCESS_URL}
      cancel_callback: ${STRIPE_CANCEL_URL}
      webhook_secret: ${STRIPE_WEBHOOK_SECRET}
      price:
        prepass: ${PROD_PREPASS}
        chat_ticket: ${PROD_CHAT_TICKET}
        slot_1: ${PROD_SLOT1}
        slot_2: ${PROD_SLOT2}
        slot_3: ${PROD_SLOT3}

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
              #scope:
              #- name
            #- profile_nickname
            # - account_email

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token:
    expiration: ${REFRESH_TOKEN_EXPIRATION}
  redirect: ${REDIRECT_URL}

server:
  domain: ${DOMAIN_NAME}

oauth:
  kakao:
    key: ${KAKAO_KEY}

logging:
  level:
    org.springframework.security: debug
    web: debug

firebase:
  config-file: firebase-service-account.json
